server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://logistica-db:5432/logistica?currentSchema=logistica
    username: utn
    password: utn123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: America/Buenos_Aires
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tpi-backend
logging:
  org.springframework.jdbc.datasource: DEBUG

services:
  transporte:
    base-url: http://ms-transporte:8082
  contenedores:
    base-url: http://ms-contenedores:8081

