services:
  contenedores:
    base-url: http://ms-contenedores:8081

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://logistica-db:5432/logistica?currentSchema=logistica
    username: utn
    password: utn123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: America/Buenos_Aires
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  org.springframework.jdbc.datasource: DEBUG

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}
    

