services:
  db:
    image: postgres:18
    container_name: logistica-db
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - pgroot:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_HOSTNAME=keycloak
      - KC_HOSTNAME_STRICT=false
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    depends_on:
      db:
        condition: service_healthy

  gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gateway
    container_name: gateway
    ports:
      - "8087:8087"
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: unless-stopped

  ms-contenedores:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ms-contenedores
    container_name: ms-contenedores
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  ms-transporte:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ms-transporte
    container_name: ms-transporte
    ports:
      - "8082:8082"
    environment: 
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      ms-contenedores:
        condition: service_started
    restart: unless-stopped

  ms-usuarios:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ms-usuarios
    container_name: ms-usuarios
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  ms-tarifas:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ms-tarifas
    container_name: ms-tarifas
    ports:
      - "8084:8084"
    depends_on:
      db:
        condition: service_healthy
      ms-transporte:
        condition: service_started
      ms-contenedores:
        condition: service_started
    restart: unless-stopped

volumes:
  pgroot:
